### ISSUE TITLE
As a teacher, I want to be able to create an exercise for a game, so that I can share my exercises with all other teachers within Tricked.

### ISSUE THREAD

**Issue by capper0074** [KasperNissen1997/TrickedKnowledgeHub#1]
# Tasks 📋
Smaller tasks that all contribute towards the completion of the larger user story.

## Analysis 📐
 - [x] #12 
 - [x] #13
 - [x] #22
 - [x] #8 
 - [x] #14
 - [x] #9 
 - [x] #33
 
## Design ✏️
 - [x] #28
 - [x] #7 
 - [x] #26 
 - [x] #29

The tasks in the Implementation section are created as the Analysis and Design phases progresses.

## Implementation 💻
 - [x] #30
 - [x] #10 
 - [x] #17 
 - [x] #31

### WPF
 - [x] #32
 - [x] #15 
 - [x] #35
 - [x] #34
 - [x] #36
 - [x] #16 

### DB
 - [x] #11 

# Acceptance Criteria ✅
This is a selection of criteria determined before any work has started on the user story. They must not change during the completion of the user story.

 - [x] Teachers can create an exercise.
 - [x] Teachers should be able to use the exercise formular provided by the system.

## Technical
 - [x] The code-behind of each created View contains minimal code.
 - [x] There are no binding errors.
 - [x] The DCD and codebase reflect each other.
 - [x] Consistency across all of the codebase, as well as any created/modified artefacts.
