### ISSUE TITLE
As a user, I want to be able to filter my live feed of exercises, so that I only see exercises that are relevant to me.

### ISSUE THREAD

**Issue by KasperNissen1997** [KasperNissen1997/TrickedKnowledgeHub#92]
# _**This user story is not yet ready.**_
_**Once this user story becomes an issue in the git repository, the '#' entries reference generalized analysis and design issues.**_

# Tasks 📋
Smaller tasks that all contribute towards the completion of the larger user story.

## Analysis 📐
 - [ ] #12 
 - [ ] #13
 - [ ] #22
 - [ ] #8 
 - [ ] #14
 - [ ] #9 
 
## Design ✏️
 - [ ] #28 
 - [ ] #7 
 - [ ] #26 
 - [ ] #29 

The tasks in the Implementation section are created as the Analysis and Design phases progresses.

### WPF

_When we've determined what Views we need, we can create tasks here related to creating ViewModels for each View, and accompanying commands._

### DB

# Acceptance Criteria ✅
This is a selection of criteria determined before any work has started on the user story. They must not change during the completion of the user story.

 - [ ] This feature should do this when that.

## Technical
 - [ ] The code-behind of each created View contains minimal code.
 - [ ] There are no binding errors.
 - [ ] The DCD and codebase reflect each other.
 - [ ] Consistency across all of the codebase, as well as any created/modified artefacts.
